overrides:
  '@sanity/types@2>@types/react': '-'

onlyBuiltDependencies:
  - '@netlify/content-engine'
  - '@parcel/watcher'
  - content-engine
  - contentful
  - es5-ext
  - esbuild
  - lmdb
  - msgpackr-extract
  - netlify-cli
  - sharp
  - unix-dgram
